import { Router } from 'express';
import { assertDatabase,supabase } from '../config/supabase';
import { CommanderRequest,requireCommander } from '../middleware/commander-auth';
import { PublicError } from '../middleware/error-handler';
import { deploymentPlanSchema,planDecisionSchema,uuidParams,validate } from '../middleware/validate';
const router=Router();router.use(requireCommander);
const windowFactor:Record<string,number>={'06:00-09:00':.82,'09:00-12:00':.68,'12:00-16:00':.61,'16:00-20:00':.9,'20:00-23:00':.55};
const km=(a:any,b:any)=>{const rad=(value:number)=>value*Math.PI/180;const dLat=rad(Number(b.latitude)-Number(a.latitude));const dLon=rad(Number(b.longitude)-Number(a.longitude));const value=Math.sin(dLat/2)**2+Math.cos(rad(Number(a.latitude)))*Math.cos(rad(Number(b.latitude)))*Math.sin(dLon/2)**2;return 6371*2*Math.asin(Math.sqrt(value))};
router.get('/',async(_req,res,next)=>{try{const data=assertDatabase(await supabase.from('deployment_plans').select('*,plan_assignments(*,junctions(name,junction_id,latitude,longitude,assigned_officers))').order('created_at',{ascending:false}).limit(20));res.json({success:true,data})}catch(error){next(error)}});
router.post('/generate',validate({body:deploymentPlanSchema}),async(req:CommanderRequest,res,next)=>{try{
  const junctions:any[]=assertDatabase(await supabase.from('junctions').select('id,name,latitude,longitude,historical_risk_score,current_risk_score,assigned_officers,required_officers').order('historical_risk_score',{ascending:false}));
  const officers:any[]=assertDatabase(await supabase.from('officers').select('id,latitude,longitude,status,available,last_location_update').eq('status','AVAILABLE').eq('available',true).not('latitude','is',null).not('longitude','is',null));
  const factor=windowFactor[req.body.time_window];const plan:any=assertDatabase(await supabase.from('deployment_plans').insert({plan_date:req.body.plan_date,time_window:req.body.time_window,source_label:'FORECAST',data_freshness:null}).select('*').single());
  const rows=junctions.map(j=>{const congestion=Math.min(1,Math.max(0,factor*(.55+.45*j.historical_risk_score/100)));const risk=Math.round((.55*j.historical_risk_score+.25*j.current_risk_score+20*congestion)*100)/100;const recommended=risk>=80?3:risk>=60?2:risk>=40?1:0;const eligible=officers.filter(o=>o.last_location_update&&Date.now()-new Date(o.last_location_update).getTime()<=300000&&km(j,o)<=6).sort((a,b)=>km(j,a)-km(j,b));return{plan_id:plan.id,junction_id:j.id,predicted_congestion:Math.round(congestion*100)/100,predicted_risk:risk,confidence:'MODELLED · REQUIRES LICENSED TRAFFIC FEED',factors:['Historical crash risk','Selected time-window pattern','Current operational risk'],recommended_officers:recommended,staffing_shortfall:Math.max(0,recommended-Number(j.assigned_officers??0)),eligible_officer_count:eligible.length,staging_time:new Date(`${req.body.plan_date}T${req.body.time_window.slice(0,5)}:00+05:30`).toISOString(),estimated_travel_minutes:eligible.length?Math.max(2,Math.ceil(km(j,eligible[0])/(24/60))):null}});
  const assignments=assertDatabase(await supabase.from('plan_assignments').insert(rows).select('*,junctions(name,junction_id,latitude,longitude,assigned_officers)'));res.status(201).json({success:true,data:{...plan,plan_assignments:assignments}})
}catch(error){next(error)}});
router.post('/:id/decision',validate({params:uuidParams,body:planDecisionSchema}),async(req:CommanderRequest,res,next)=>{try{const{data,error}=await supabase.rpc('decide_deployment_plan',{p_plan_id:req.params.id,p_decision:req.body.decision,p_commander_id:req.commanderId!,p_notes:req.body.notes??null});if(error)throw error;if(data?.code==='CONFLICT')throw new PublicError(409,data.message);if(data?.code==='NOT_FOUND')throw new PublicError(404,data.message);if(data?.code==='INVALID')throw new PublicError(400,data.message);res.json({success:true,data:data.plan})}catch(error){next(error)}});
export default router;
