import { useCallback,useEffect,useRef,useState } from 'react';
import { Alert,ScrollView,Text,TouchableOpacity,View } from 'react-native';import * as Location from 'expo-location';
import { SafeAreaProvider,SafeAreaView } from 'react-native-safe-area-context';
import { ApiError,api,onUnauthorized,restoreOfficerSession } from './services/api';import { startAssignmentPolling } from './services/polling';
import { Assignment,Officer,Point,Screen } from './src/types';import { s } from './src/theme';import { LoginScreen } from './src/screens/LoginScreen';import { DutyScreen } from './src/screens/DutyScreen';import { AssignmentScreen } from './src/screens/AssignmentScreen';import { IncidentReportScreen } from './src/screens/IncidentReportScreen';import { NotesScreen } from './src/screens/NotesScreen';
const message=(error:unknown)=>error instanceof Error?error.message:'Operation failed. Please retry.';
function SafeFlowApp(){const[officer,setOfficer]=useState<Officer|null>(null);const[ready,setReady]=useState(false);const[onDuty,setOnDuty]=useState(false);const[screen,setScreen]=useState<Screen>('duty');const[point,setPoint]=useState<Point|null>(null);const[assignment,setAssignment]=useState<Assignment|null>(null);const[permission,setPermission]=useState('not requested');const[lastLocation,setLastLocation]=useState<Date>();const[lastSync,setLastSync]=useState<Date>();const[syncError,setSyncError]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const watcher=useRef<Location.LocationSubscription|null>(null);const polling=useRef<(()=>void)|null>(null);
const stopLocal=useCallback(()=>{watcher.current?.remove();watcher.current=null;polling.current?.();polling.current=null},[]);
const clearLocalSession=useCallback(async()=>{await api.logout();setOfficer(null);setOnDuty(false);setPoint(null);setAssignment(null);setScreen('duty')},[]);
const finishLocalLogout=useCallback(async()=>{stopLocal();await clearLocalSession()},[clearLocalSession,stopLocal]);
const signOut=useCallback(async()=>{if(!officer){await finishLocalLogout();return}setBusy(true);setError('');if(!onDuty){await finishLocalLogout();setBusy(false);return}try{await api.stopDuty(officer.id);await finishLocalLogout()}catch(reason){setBusy(false);if(reason instanceof ApiError&&reason.status===401)return;stopLocal();Alert.alert('Server duty may still be active','SafeFlow could not confirm Stop Duty. Local location tracking and assignment polling have stopped.',[{text:'Retry',onPress:signOut},{text:'Force Local Logout',style:'destructive',onPress:()=>Alert.alert('Confirm local logout','Your secure session will be removed, but the server may still show you as active until a commander corrects it or you sign in and stop duty successfully.',[{text:'Cancel',style:'cancel'},{text:'Force Local Logout',style:'destructive',onPress:()=>{void clearLocalSession()}}])}])}},[clearLocalSession,finishLocalLogout,officer,onDuty,stopLocal]);
useEffect(()=>{restoreOfficerSession().then(value=>{setOfficer(value);const active=!!value&&value.status!=='OFF_DUTY';setOnDuty(false);if(active)setError('Server duty may still be active. Tap Start Duty to resume foreground location sharing.');setReady(true)}).catch(()=>setReady(true));return onUnauthorized(()=>{stopLocal();setOfficer(null);setOnDuty(false);setPoint(null);setAssignment(null);setScreen('duty');setError('Your session expired. Sign in again.')})},[stopLocal]);
const refresh=useCallback(async()=>{if(!officer)return;try{setAssignment(await api.assignment(officer.id));setSyncError('')}catch(reason){if(reason instanceof ApiError&&reason.status===404){setAssignment(null);setSyncError('')}else setSyncError(message(reason))}finally{setLastSync(new Date())}},[officer]);
useEffect(()=>{if(!officer||!onDuty)return;polling.current=startAssignmentPolling(refresh);return()=>{polling.current?.();polling.current=null}},[officer,onDuty,refresh]);
useEffect(()=>()=>stopLocal(),[stopLocal]);
async function sendLocation(location:Location.LocationObject){if(!officer)return;const payload={latitude:location.coords.latitude,longitude:location.coords.longitude,accuracy:location.coords.accuracy??undefined,recorded_at:new Date(location.timestamp).toISOString()};setPoint(payload);try{await api.location(officer.id,payload);setLastLocation(new Date())}catch(reason){setSyncError(message(reason))}}
async function startDuty(){if(!officer)return;setBusy(true);setError('');try{const result=await Location.requestForegroundPermissionsAsync();setPermission(result.status);if(result.status!=='granted')throw new Error('Foreground location permission is required to start duty.');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});const payload={latitude:current.coords.latitude,longitude:current.coords.longitude,accuracy:current.coords.accuracy??undefined,recorded_at:new Date(current.timestamp).toISOString()};await api.startDuty(officer.id,payload);setPoint(payload);setOnDuty(true);setOfficer({...officer,status:'AVAILABLE'});setLastLocation(new Date());watcher.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:30000,distanceInterval:20},sendLocation)}catch(reason){setError(message(reason));Alert.alert('Duty not started',message(reason))}finally{setBusy(false)}}
function confirmStop(){Alert.alert('Stop duty?','Location sharing and assignment polling will stop.',[{text:'Cancel',style:'cancel'},{text:'Stop duty',style:'destructive',onPress:stopDuty}])}
async function stopDuty(){if(!officer)return;stopLocal();setBusy(true);try{await api.stopDuty(officer.id);setOnDuty(false);setPoint(null);setAssignment(null);setOfficer({...officer,status:'OFF_DUTY'})}catch(reason){setError(`Location sharing stopped locally, but server duty status may still be active. Retry stop duty. ${message(reason)}`)}finally{setBusy(false)}}
async function login(values:{badge_code:string;pin:string}){setBusy(true);setError('');try{const value=await api.login(values.badge_code,values.pin);setOfficer(value);setOnDuty(value.status!=='OFF_DUTY')}catch(reason){setError(message(reason))}finally{setBusy(false)}}
async function action(operation:()=>Promise<unknown>,success:string,after?:()=>void){setBusy(true);try{await operation();after?.();Alert.alert('Success',success)}catch(reason){Alert.alert('Unable to complete action',message(reason))}finally{setBusy(false)}}
if(!ready)return <SafeAreaView style={s.shell}><View style={s.center}><Text style={s.copy}>Restoring secure session…</Text></View></SafeAreaView>;if(!officer)return <LoginScreen login={login} error={error} busy={busy}/>;
const body=screen==='duty'?<DutyScreen officer={officer} onDuty={onDuty} permission={permission} point={point} lastUpdate={lastLocation} assignment={assignment} busy={busy} start={startDuty} stop={confirmStop} openAssignment={()=>setScreen('assignment')}/>:screen==='assignment'?<AssignmentScreen item={assignment} lastSync={lastSync} error={syncError} retry={refresh} busy={busy} accept={()=>assignment&&action(()=>api.accept(officer.id,assignment.id),'Assignment accepted.',refresh)} reject={reason=>assignment&&action(()=>api.reject(officer.id,assignment.id,reason),'Assignment rejected.',()=>setAssignment(null))} arrive={()=>assignment&&action(()=>api.arrival(officer.id,assignment.junction_id),'Arrival confirmed.',()=>setAssignment(null))}/>:screen==='incident'?<IncidentReportScreen point={point} busy={busy} submit={payload=>action(()=>api.report(officer.id,{...payload,...point}),'Field report submitted.')}/>:screen==='notes'?<NotesScreen busy={busy} submit={payload=>action(()=>api.note(officer.id,payload),'Operational note submitted.')}/>:<View style={s.card}><Text style={s.kicker}>PROFILE & PRIVACY</Text><Text style={s.heading}>{officer.name}</Text><Text style={[s.copy,s.mask]}>Badge ••••{officer.badge_code.slice(-3)}</Text><Text style={s.copy}>Duty: {onDuty?'ACTIVE':'OFF DUTY'}</Text><Text style={s.copy}>Location sharing: {onDuty?'Foreground only':'OFF'}</Text><Text style={s.small}>SafeFlow shares location only during an active duty session. Background GPS and push notifications are not enabled.</Text><TouchableOpacity style={s.danger} onPress={()=>Alert.alert('Log out?','This removes the secure officer session and stops local tracking.',[{text:'Cancel',style:'cancel'},{text:'Log out',style:'destructive',onPress:signOut}])}><Text style={s.lightText}>Log out securely</Text></TouchableOpacity></View>;
return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.content}>{error&&<Text style={s.error}>{error}</Text>}{body}</ScrollView><View style={s.tabs}>{(['duty','assignment','incident','notes','profile'] as Screen[]).map(item=><TouchableOpacity key={item} style={s.tab} disabled={!onDuty&&['incident','notes'].includes(item)} onPress={()=>setScreen(item)}><Text style={[s.tabText,screen===item&&s.tabActive]}>{item.toUpperCase()}</Text></TouchableOpacity>)}</View></SafeAreaView>}

export default function App(){return <SafeAreaProvider><SafeFlowApp/></SafeAreaProvider>}
