import { useEffect,useState } from 'react';
import { Alert,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from 'react-native';
import * as Location from 'expo-location';
import { api } from './services/api';import { subscribeToAssignments } from './services/realtime';
type Officer={id:string;name:string;badge_code:string;status:string};type Assignment={id:string;junction_id:string;recommendation_text:string;travel_time_minutes:number;junctions?:{name:string}};
export default function App(){const[officer,setOfficer]=useState<Officer|null>(null);const[badge,setBadge]=useState('');const[pin,setPin]=useState('');const[assignment,setAssignment]=useState<Assignment|null>(null);const[onDuty,setOnDuty]=useState(false);const[busy,setBusy]=useState(false);
async function refresh(){if(!officer)return;try{const result=await api.assignments(officer.id);setAssignment(result.data[0]??null)}catch(error:any){Alert.alert('Assignment refresh failed',error.message)}}
useEffect(()=>officer?subscribeToAssignments(officer.id,refresh):undefined,[officer]);
async function login(){try{setBusy(true);setOfficer(await api.officerLogin(badge.trim(),pin));setPin('')}catch(error:any){Alert.alert('Login failed',error.message)}finally{setBusy(false)}}
async function position(){const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Location permission is required');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});return{latitude:current.coords.latitude,longitude:current.coords.longitude,accuracy:current.coords.accuracy??undefined}}
async function start(){try{setBusy(true);const point=await position();await api.startDuty(officer!.id,point);await api.location(officer!.id,point);setOnDuty(true);await refresh()}catch(error:any){Alert.alert('Unable to start duty',error.message)}finally{setBusy(false)}}
async function stop(){try{await api.stopDuty(officer!.id);setOnDuty(false)}catch(error:any){Alert.alert('Unable to stop duty',error.message)}}
async function arrive(){if(!assignment)return;try{await api.arrival(officer!.id,assignment.junction_id);setAssignment(null);Alert.alert('Arrival confirmed')}catch(error:any){Alert.alert('Arrival failed',error.message)}}
if(!officer)return <SafeAreaView style={s.shell}><View style={s.panel}><Text style={s.kicker}>NAGPUR TRAFFIC POLICE</Text><Text style={s.title}>Officer field link</Text><TextInput style={s.input} value={badge} onChangeText={setBadge} placeholder="Badge code" placeholderTextColor="#789" autoCapitalize="characters"/><TextInput style={s.input} value={pin} onChangeText={setPin} placeholder="Secure PIN" placeholderTextColor="#789" secureTextEntry keyboardType="number-pad"/><TouchableOpacity style={s.button} onPress={login} disabled={busy}><Text style={s.buttonText}>{busy?'Verifying…':'Sign in'}</Text></TouchableOpacity></View></SafeAreaView>;
return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.panel}><Text style={s.kicker}>SIGNED OFFICER SESSION</Text><Text style={s.title}>{officer.name}</Text><Text style={s.copy}>{officer.badge_code} · {onDuty?'ON DUTY':'OFF DUTY'}</Text><TouchableOpacity style={s.button} onPress={onDuty?stop:start}><Text style={s.buttonText}>{onDuty?'Stop duty':'Start duty'}</Text></TouchableOpacity>{assignment?<View style={s.card}><Text style={s.kicker}>COMMANDER-APPROVED ASSIGNMENT</Text><Text style={s.heading}>{assignment.junctions?.name??assignment.recommendation_text}</Text><Text style={s.copy}>{assignment.travel_time_minutes} min estimated travel</Text><TouchableOpacity style={s.button} onPress={arrive}><Text style={s.buttonText}>Confirm arrival</Text></TouchableOpacity></View>:<View style={s.card}><Text style={s.heading}>No active assignment</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:'#071019'},panel:{flexGrow:1,justifyContent:'center',padding:26,gap:14},kicker:{color:'#57d2b7',letterSpacing:2,fontSize:10,fontWeight:'800'},title:{color:'#edf4f7',fontSize:34,fontWeight:'800'},heading:{color:'#edf4f7',fontSize:20,fontWeight:'800'},copy:{color:'#9aacb6'},input:{backgroundColor:'#0f1d27',borderColor:'#293c48',borderWidth:1,color:'white',padding:15,borderRadius:11},button:{backgroundColor:'#51d2b6',padding:16,borderRadius:11,alignItems:'center'},buttonText:{color:'#06130f',fontWeight:'800'},card:{backgroundColor:'#0e1b24',borderColor:'#253744',borderWidth:1,borderRadius:16,padding:20,gap:12}});
