import { Controller,useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Alert,Linking,Share,Text,TextInput,TouchableOpacity,View } from 'react-native';
import { useEffect,useMemo,useState } from 'react';
import { api } from '../../services/api';
import { JunctionOption,Point } from '../types';
import { s } from '../theme';
const types=['COLLISION','CONGESTION','OBSTRUCTION','MEDICAL_EMERGENCY','OTHER'] as const;
const schema=z.object({incident_type:z.enum(types),severity:z.number().min(0).max(1),note:z.string().trim().min(3,'Describe the field incident').max(2000)});type Form=z.infer<typeof schema>;
const distance=(a:Point,b:JunctionOption)=>{const rad=(value:number)=>value*Math.PI/180;const dLat=rad(b.latitude-a.latitude);const dLon=rad(b.longitude-a.longitude);const value=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.asin(Math.sqrt(value))};
const requestId=()=>`xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx`.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return(c==='x'?r:(r&3)|8).toString(16)});
export function IncidentReportScreen({officerId,point,submit,busy}:{officerId:string;point:Point|null;submit:(data:any)=>Promise<{id:string;incident_id?:string}>;busy:boolean}){
  const{control,handleSubmit,setValue,watch,formState:{errors}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{incident_type:'COLLISION',severity:.5,note:''}});const severity=watch('severity');const incidentType=watch('incident_type');
  const[junctions,setJunctions]=useState<JunctionOption[]>([]);const[query,setQuery]=useState('');const[selected,setSelected]=useState<JunctionOption|null>(null);const[away,setAway]=useState(false);const[emergency,setEmergency]=useState(false);const[pendingId,setPendingId]=useState(requestId());const[result,setResult]=useState('');const[loadError,setLoadError]=useState('');
  useEffect(()=>{api.junctions(officerId).then(setJunctions).catch(error=>setLoadError(error instanceof Error?error.message:'Unable to load junctions'))},[officerId]);
  const nearest=useMemo(()=>point&&junctions.length?[...junctions].map(item=>({item,km:distance(point,item)})).sort((a,b)=>a.km-b.km)[0]:null,[junctions,point]);
  const matches=useMemo(()=>query.trim()?junctions.filter(item=>`${item.name} ${item.junction_id}`.toLowerCase().includes(query.trim().toLowerCase())).slice(0,6):[],[junctions,query]);
  const emergencyNumber=process.env.EXPO_PUBLIC_EMERGENCY_NUMBER;const configured=!!emergencyNumber&&/^\d{3,15}$/.test(emergencyNumber);
  const callEmergency=()=>Alert.alert('Open emergency dialer?','PoliceOps will open your phone dialer. It cannot confirm that a call is answered or assistance is dispatched.',[{text:'Cancel',style:'cancel'},{text:'Open dialer',onPress:async()=>{if(!configured)return Alert.alert('Emergency number not configured','Ask the administrator to configure the emergency number.');const url=`tel:${emergencyNumber}`;if(await Linking.canOpenURL(url))await Linking.openURL(url);else Alert.alert('Dialer unavailable',`Call ${emergencyNumber} manually.`)}}]);
  const shareLocation=()=>{if(!point)return Alert.alert('Location unavailable','Start duty and acquire a current location first.');const latitude=point.latitude.toFixed(3);const longitude=point.longitude.toFixed(3);Alert.alert('Share approximate incident location?','The system share sheet will open only after confirmation. Do not add personal information.',[{text:'Cancel',style:'cancel'},{text:'Share',onPress:()=>void Share.share({message:`PoliceOps field incident: ${incidentType.replace('_',' ')}. Approximate map location: https://maps.google.com/?q=${latitude},${longitude}. No dispatch is confirmed by PoliceOps.`})}])};
  async function send(data:Form){if(!point)throw new Error('Current duty location is required');setResult('');const response=await submit({...data,...point,junction_id:away?null:selected?.id??null,client_request_id:pendingId,emergency_requested:emergency});setResult(`Report accepted · reference ${response.id.slice(0,8).toUpperCase()}`);setPendingId(requestId())}
  return <View style={s.card}><Text style={s.kicker}>FIELD INCIDENT · OPERATIONAL RECORD</Text><Text style={s.copy}>{point?'Current foreground duty location available.':'GPS unavailable. Start duty and acquire a current location.'}</Text>{result&&<Text style={s.success}>{result}</Text>}
    <View style={s.row}><TouchableOpacity style={s.danger} onPress={callEmergency}><Text style={s.lightText}>Request emergency assistance</Text></TouchableOpacity><TouchableOpacity style={s.buttonSecondary} onPress={shareLocation}><Text style={s.lightText}>Share incident location</Text></TouchableOpacity></View><Text style={s.small}>These actions require confirmation. PoliceOps does not contact a hospital or confirm dispatch.</Text>
    <Controller control={control} name="incident_type" render={({field})=><View style={s.sliderRow}>{types.map(type=><TouchableOpacity key={type} style={[s.severity,field.value===type&&s.severityActive]} onPress={()=>field.onChange(type)}><Text style={field.value===type?s.buttonText:s.lightText}>{type.replace('_',' ')}</Text></TouchableOpacity>)}</View>}/><Text style={s.label}>Severity {Math.round(severity*100)}%</Text><View style={s.sliderRow}>{[.2,.4,.6,.8,1].map(value=><TouchableOpacity key={value} style={[s.severity,severity===value&&s.severityActive]} onPress={()=>setValue('severity',value)}><Text style={severity===value?s.buttonText:s.lightText}>{value}</Text></TouchableOpacity>)}</View>
    <Text style={s.label}>Optional junction</Text><TextInput style={s.input} value={query} onChangeText={setQuery} placeholder="Search junction name" placeholderTextColor="#718591"/>{loadError&&<Text style={s.error}>{loadError}</Text>}{matches.map(item=><TouchableOpacity key={item.id} style={s.buttonSecondary} onPress={()=>{setSelected(item);setAway(false);setQuery(item.name)}}><Text style={s.lightText}>{item.name}</Text></TouchableOpacity>)}
    {nearest&&<TouchableOpacity style={s.buttonSecondary} onPress={()=>{if(nearest.km>10)return Alert.alert('Nearest junction is too far',`${nearest.item.name} is approximately ${nearest.km.toFixed(1)} km away. Choose “away from listed junctions” or select manually.`);setSelected(nearest.item);setAway(false);setQuery(nearest.item.name)}}><Text style={s.lightText}>Use nearest: {nearest.item.name} · {nearest.km.toFixed(1)} km</Text></TouchableOpacity>}<TouchableOpacity style={s.buttonSecondary} onPress={()=>{setAway(true);setSelected(null);setQuery('')}}><Text style={s.lightText}>{away?'✓ ':''}Incident is away from listed junctions</Text></TouchableOpacity>
    <Controller control={control} name="note" render={({field})=><TextInput multiline style={[s.input,{minHeight:110}]} value={field.value} onChangeText={field.onChange} placeholder="Describe what happened and the current road condition" placeholderTextColor="#718591"/>}/>{errors.note&&<Text style={s.error}>{String(errors.note.message)}</Text>}
    <TouchableOpacity style={s.row} onPress={()=>setEmergency(value=>!value)}><Text style={s.pill}>{emergency?'✓ EMERGENCY ASSISTANCE REQUESTED':'Emergency assistance not requested'}</Text></TouchableOpacity><TouchableOpacity style={s.button} disabled={busy||!point} onPress={handleSubmit(send)}><Text style={s.buttonText}>{busy?'Submitting…':result?'Submit another report':'Submit incident report'}</Text></TouchableOpacity>
  </View>
}
