import * as SecureStore from 'expo-secure-store';
import { Assignment,Officer,Point } from '../src/types';
const baseUrl=process.env.EXPO_PUBLIC_API_URL??'http://localhost:3001/api';const tokenKey='safeflow_officer_token';const profileKey='safeflow_officer_profile';let token:string|null=null;let unauthorized:()=>void=()=>undefined;
export class ApiError extends Error{constructor(message:string,public status:number){super(message)}}
export function onUnauthorized(callback:()=>void){unauthorized=callback;return()=>{unauthorized=()=>undefined}}
export async function restoreOfficerSession(){token=await SecureStore.getItemAsync(tokenKey);const profile=await SecureStore.getItemAsync(profileKey);return token&&profile?JSON.parse(profile) as Officer:null}
async function saveSession(value:string,officer:Officer){token=value;await Promise.all([SecureStore.setItemAsync(tokenKey,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY}),SecureStore.setItemAsync(profileKey,JSON.stringify(officer),{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY})])}
export async function clearOfficerSession(){token=null;await Promise.all([SecureStore.deleteItemAsync(tokenKey),SecureStore.deleteItemAsync(profileKey)])}
async function request<T>(path:string,options?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(`${baseUrl}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...options?.headers}})}catch{throw new ApiError('Network unavailable. Check your connection and retry.',0)}let body:any={};try{body=await response.json()}catch{}if(!response.ok){if(response.status===401){await clearOfficerSession();unauthorized()}throw new ApiError(friendly(response.status,body.error),response.status)}return body}
function friendly(status:number,message?:string){if(status===400)return message??'Check the entered information.';if(status===401)return'Session expired. Sign in again.';if(status===403)return'You cannot perform this action.';if(status===404)return message??'Requested item was not found.';if(status===409)return message??'This action was already completed.';if(status===429)return'Too many attempts. Wait and retry.';if(status>=500)return'Service temporarily unavailable.';return message??'Request failed.'}
export const api={
  login:async(badge_code:string,pin:string)=>{const result=await request<{token:string;officer:Officer}>('/auth/officer-login',{method:'POST',body:JSON.stringify({badge_code,pin})});await saveSession(result.token,result.officer);return result.officer},
  startDuty:(id:string,point:Point)=>request<any>(`/officers/${id}/duty/start`,{method:'POST',body:JSON.stringify(point)}),stopDuty:(id:string)=>request<any>(`/officers/${id}/duty/stop`,{method:'POST'}),location:(id:string,point:Point)=>request<any>(`/officers/${id}/location`,{method:'POST',body:JSON.stringify(point)}),
  assignment:async(id:string)=>{const result=await request<{data:Assignment}>(`/officers/${id}/assignment`);return result.data},accept:(id:string,recommendationId:string)=>request<any>(`/officers/${id}/assignment/${recommendationId}/accept`,{method:'POST',body:'{}'}),reject:(id:string,recommendationId:string,reason:string)=>request<any>(`/officers/${id}/assignment/${recommendationId}/reject`,{method:'POST',body:JSON.stringify({reason})}),arrival:(id:string,junction_id:string)=>request<any>(`/officers/${id}/arrival`,{method:'POST',body:JSON.stringify({junction_id})}),note:(id:string,payload:{note:string;junction_id?:string;incident_id?:string})=>request<any>(`/officers/${id}/notes`,{method:'POST',body:JSON.stringify(payload)}),report:(id:string,payload:any)=>request<any>(`/officers/${id}/report-incident`,{method:'POST',body:JSON.stringify(payload)}),logout:clearOfficerSession,
};
