import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, LogOut, MapPinned, Radio, RefreshCw, ShieldCheck, Users, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import OperationsMap from '../components/OperationsMap';
import RecommendationCard from '../components/RecommendationCard';
import { baselineAPI, incidentsAPI, junctionsAPI, officersAPI, recommendationsAPI } from '../services/api';
import { RealtimeStatus, subscribeToOperations } from '../services/realtime';
import { BaselineMetrics, Junction, Officer, Recommendation } from '../types';

type Notice = { tone:'success'|'error'; message:string } | null;

export default function DashboardPage() {
  const navigate=useNavigate(); const [junctions,setJunctions]=useState<Junction[]>([]); const [officers,setOfficers]=useState<Officer[]>([]);
  const [recommendations,setRecommendations]=useState<Recommendation[]>([]); const [baseline,setBaseline]=useState<BaselineMetrics|null>(null);
  const [selected,setSelected]=useState<Junction|null>(null); const [dialog,setDialog]=useState(false); const [severity,setSeverity]=useState(.8);
  const [incidentType,setIncidentType]=useState('COLLISION'); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
  const [actionBusy,setActionBusy]=useState(false); const [notice,setNotice]=useState<Notice>(null); const [lastUpdated,setLastUpdated]=useState<Date>();
  const [realtimeStatus,setRealtimeStatus]=useState<RealtimeStatus>('CONNECTING');

  const load=useCallback(async(silent=false)=>{if(!silent)setRefreshing(true);try{const[j,o,r,b]=await Promise.all([junctionsAPI.getAll(),officersAPI.getAll(),recommendationsAPI.getAll(),baselineAPI.getMetrics()]);setJunctions(j.data.data);setOfficers(o.data.data);setRecommendations(r.data.data);setBaseline(b.data.data.metrics);setLastUpdated(new Date());setSelected(current=>current?j.data.data.find((item:Junction)=>item.id===current.id)??current:j.data.data[0]??null)}catch(error:any){setNotice({tone:'error',message:error.response?.data?.error??'Unable to load live operations data.'})}finally{setLoading(false);setRefreshing(false)}},[]);
  useEffect(()=>{const handleStatus=(event:Event)=>setRealtimeStatus((event as CustomEvent<RealtimeStatus>).detail);window.addEventListener('safeflow:realtime-status',handleStatus);load();const unsubscribe=subscribeToOperations(()=>load(true));return()=>{window.removeEventListener('safeflow:realtime-status',handleStatus);unsubscribe()}},[load]);
  const high=useMemo(()=>junctions.filter(j=>['HIGH','CRITICAL'].includes(j.current_risk_level)),[junctions]); const available=officers.filter(o=>o.status==='AVAILABLE').length;
  const realtime=realtimeStatus==='SUBSCRIBED'?{label:'Realtime linked',detail:'Database updates refresh automatically'}:realtimeStatus==='CONNECTING'?{label:'Connecting',detail:'Establishing the database update channel'}:realtimeStatus==='UNCONFIGURED'?{label:'Realtime not configured',detail:'Refresh manually or retry connection'}:{label:'Realtime unavailable',detail:'Refresh manually or retry connection'};

  async function simulate(){if(!selected||actionBusy)return;setActionBusy(true);try{const response=await incidentsAPI.simulate({junction_id:selected.id,severity,incident_type:incidentType});setDialog(false);setNotice({tone:'success',message:`Simulation created at ${selected.name}. Risk is now ${response.data.data.junction.current_risk_score}.`});await load(true)}catch(error:any){setNotice({tone:'error',message:error.response?.data?.error??'Simulation failed. Check API logs and try again.'})}finally{setActionBusy(false)}}
  async function accept(id:string){setActionBusy(true);try{await recommendationsAPI.accept(id);setNotice({tone:'success',message:'Deployment accepted and audit log recorded.'});await load(true)}catch(error:any){setNotice({tone:'error',message:error.response?.data?.error??'Could not accept deployment.'})}finally{setActionBusy(false)}}
  async function reject(id:string){const reason=window.prompt('Reason for rejecting this recommendation:');if(!reason)return;setActionBusy(true);try{await recommendationsAPI.reject(id,reason);setNotice({tone:'success',message:'Recommendation rejected and audit log recorded.'});await load(true)}catch(error:any){setNotice({tone:'error',message:error.response?.data?.error??'Could not reject recommendation.'})}finally{setActionBusy(false)}}
  function logout(){localStorage.removeItem('safeflow_token');navigate('/')}
  if(loading)return <main className="loading-screen"><Radio className="pulse"/><div><strong>Establishing command link</strong><span>Loading live Supabase operations…</span></div></main>;

  return <main className="dashboard">
    <header className="topbar"><div className="brand"><div className="brand-mark small">NS</div><div><strong>Nagpur SafeFlow</strong><span>Traffic Command & Decision Support</span></div></div><div className={`system-status realtime-${realtimeStatus.toLowerCase()}`} title={realtime.detail}><i/> {realtime.label}</div><div className="header-actions"><button className="icon-button" onClick={()=>load()} disabled={refreshing}><RefreshCw size={17} className={refreshing?'spin':''}/> Refresh</button><button className="icon-button" onClick={logout}><LogOut size={17}/> Logout</button></div></header>
    {notice&&<div className={`notice ${notice.tone}`}>{notice.tone==='success'?<CheckCircle2/>:<AlertTriangle/>}<span>{notice.message}</span><button onClick={()=>setNotice(null)}><X/></button></div>}
    <section className="command-head"><div><span className="eyebrow">Unified operational picture</span><h1>Traffic risk command centre</h1><p>Evidence-led priorities, live field coverage, and commander-controlled deployment.</p></div><div className="command-actions"><small>Updated {lastUpdated?.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small><button className="button danger" onClick={()=>{setSelected(selected??high[0]??junctions[0]);setDialog(true)}} disabled={!junctions.length}><AlertTriangle size={18}/> Simulate incident</button></div></section>
    <section className="metrics"><Metric icon={<MapPinned/>} label="Monitored junctions" value={junctions.length} meta="Evidence registry"/><Metric icon={<AlertTriangle/>} label="High / critical" value={high.length} meta={`${high.filter(j=>j.is_unmanned).length} currently unmanned`}/><Metric icon={<Users/>} label="Available officers" value={available} meta={`${officers.length} total force`}/><Metric icon={<ShieldCheck/>} label="Projected coverage" value={`${baseline?.recommendedHighRiskCoverage??0}%`} meta={`${baseline?.staticHighRiskCoverage??0}% current baseline`}/></section>
    <section className="operations-grid"><div className="map-card"><SectionTitle eyebrow="Live geography" title="Risk & field coverage"><div className="legend"><span><i className="critical"/>Critical</span><span><i className="high"/>High</span><span><i className="officer"/>Officer</span></div></SectionTitle><OperationsMap junctions={junctions} officers={officers} selectedId={selected?.id} onSelect={setSelected}/></div><div className="ranking-card"><SectionTitle eyebrow="Priority queue" title="Highest current risk"><span className="queue-count">{junctions.length} sites</span></SectionTitle><div className="risk-list">{junctions.map((j,index)=><button key={j.id} onClick={()=>setSelected(j)} className={selected?.id===j.id?'active':''}><b>{String(index+1).padStart(2,'0')}</b><span><strong>{j.name}</strong><small>{j.junction_id} · {j.confidence}</small></span><em className={`risk ${j.current_risk_level.toLowerCase()}`}>{j.current_risk_score}</em><i className={j.is_unmanned?'unmanned':''}>{j.is_unmanned?'Unmanned':`${j.assigned_officers} deployed`}</i></button>)}</div></div></section>
    {selected&&<section className="detail-panel"><div className="junction-summary"><span className="eyebrow">Selected junction · {selected.junction_id}</span><h2>{selected.name}</h2><div className="history-strip"><span><b>{selected.historical_crashes}</b> crashes</span><span><b>{selected.fatalities}</b> fatalities</span><span><b>{selected.major_injuries}</b> major injuries</span><span><b>{selected.confidence}</b> confidence</span></div>{selected.evidence_url&&<a href={selected.evidence_url} target="_blank" rel="noreferrer">Open attributed evidence source ↗</a>}</div><div className={`risk-display ${selected.current_risk_level.toLowerCase()}`}><span>Current risk</span><strong>{selected.current_risk_score}</strong><em>{selected.current_risk_level}</em></div><div className="factor-grid"><Factor label="Congestion" value={selected.current_congestion}/><Factor label="Incident" value={selected.current_incident}/><Factor label="Violations" value={selected.current_violations}/><span>Field coverage<b>{selected.assigned_officers}</b></span></div></section>}
    <section className="recommendations"><SectionTitle eyebrow="Explainable allocation" title="Pending recommendations"><span className="queue-count">{recommendations.length} awaiting review</span></SectionTitle>{recommendations.length?recommendations.map(item=><RecommendationCard key={item.id} item={item} onAccept={()=>accept(item.id)} onReject={()=>reject(item.id)}/>):<div className="empty-state"><ShieldCheck/><div><strong>No recommendations require review</strong><span>New high-risk coverage gaps will appear here in realtime.</span></div></div>}</section>
    {baseline&&<section className="impact"><SectionTitle eyebrow="Measured decision support" title="Static vs AI-assisted deployment"><span className="queue-count">Live calculation</span></SectionTitle><div className="impact-grid"><Impact label="High-risk coverage" before={baseline.staticHighRiskCoverage} after={baseline.recommendedHighRiskCoverage} suffix="%"/><Impact label="Unmanned priority sites" before={baseline.staticUnmannedCount} after={baseline.recommendedUnmannedCount}/><Impact label="Response time" before={baseline.staticResponseTime} after={baseline.recommendedResponseTime} suffix=" min" icon={<Clock3/>}/></div></section>}
    {dialog&&selected&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="modal-icon"><AlertTriangle/></div><span className="eyebrow">Controlled & clearly labeled simulation</span><h2>{selected.name}</h2><p>This creates an auditable simulated incident, recalculates current risk, and may generate a recommendation. Historical evidence remains unchanged.</p><label>Incident type<select value={incidentType} onChange={e=>setIncidentType(e.target.value)}><option value="COLLISION">Vehicle collision</option><option value="CONGESTION">Severe congestion</option><option value="OBSTRUCTION">Road obstruction</option></select></label><label>Severity <b>{Math.round(severity*100)}%</b><input type="range" min="0.1" max="1" step="0.1" value={severity} onChange={e=>setSeverity(Number(e.target.value))}/><div className="range-labels"><span>Low</span><span>Critical</span></div></label><div className="decision-actions"><button className="button danger" onClick={simulate} disabled={actionBusy}>{actionBusy?'Running simulation…':'Run simulation'}</button><button className="button ghost" onClick={()=>setDialog(false)} disabled={actionBusy}>Cancel</button></div></div></div>}
  </main>;
}

function SectionTitle({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</div>}
function Metric({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string|number;meta:string}){return <article className="metric"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>}
function Factor({label,value}:{label:string;value:number}){const pct=Math.round((value??0)*100);return <span>{label}<b>{pct}%</b><i><em style={{width:`${pct}%`}}/></i></span>}
function Impact({label,before,after,suffix='',icon}:{label:string;before:number;after:number;suffix?:string;icon?:React.ReactNode}){return <article className="impact-row">{icon}<span>{label}</span><div><b>{before}{suffix}</b><i>→</i><strong>{after}{suffix}</strong></div></article>}
