import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import authRoutes from './routes/auth.routes';
import baselineRoutes from './routes/baseline.routes';
import incidentsRoutes from './routes/incidents.routes';
import junctionsRoutes from './routes/junctions.routes';
import officersRoutes from './routes/officers.routes';
import recommendationsRoutes from './routes/recommendations.routes';
import decisionsRoutes from './routes/decisions.routes';

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.WEB_ORIGIN?.split(',') ?? true }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('tiny'));
app.get('/health', (_req, res) => res.json({ status: 'ok', database: 'supabase', timestamp: new Date().toISOString() }));
app.use('/api/auth', authRoutes);
app.use('/api/junctions', junctionsRoutes);
app.use('/api/officers', officersRoutes);
app.use('/api/incidents', incidentsRoutes);
app.use('/api/recommendations', recommendationsRoutes);
app.use('/api/decisions', decisionsRoutes);
app.use('/api/baseline', baselineRoutes);
app.use((error: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(error);
  res.status(500).json({ success: false, error: error.message });
});
export default app;
