import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import authRoutes from './routes/auth.routes';
import baselineRoutes from './routes/baseline.routes';
import incidentsRoutes from './routes/incidents.routes';
import junctionsRoutes from './routes/junctions.routes';
import officersRoutes from './routes/officers.routes';
import recommendationsRoutes from './routes/recommendations.routes';
import decisionsRoutes from './routes/decisions.routes';
import { errorHandler,requestId } from './middleware/error-handler';

const app = express();
app.use(helmet());
const allowedOrigins=(process.env.WEB_ORIGIN??'').split(',').map(value=>value.trim()).filter(Boolean);
if(process.env.NODE_ENV==='production'&&!allowedOrigins.length)throw new Error('WEB_ORIGIN is required in production');
app.use(cors({origin:(origin,callback)=>{if(!origin||allowedOrigins.includes(origin)||(process.env.NODE_ENV!=='production'&&!allowedOrigins.length))return callback(null,true);return callback(new Error('Origin not allowed'))}}));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('tiny'));
app.use(requestId);
app.get('/api/health', (_req, res) => res.json({ status: 'ok', database: 'supabase', timestamp: new Date().toISOString() }));
app.use('/api/auth', authRoutes);
app.use('/api/junctions', junctionsRoutes);
app.use('/api/officers', officersRoutes);
app.use('/api/incidents', incidentsRoutes);
app.use('/api/recommendations', recommendationsRoutes);
app.use('/api/decisions', decisionsRoutes);
app.use('/api/baseline', baselineRoutes);
app.use(errorHandler);
export default app;
